./BRKGA >> resultados00.txt
./BRKGA >> resultados01.txt
./BRKGA >> resultados02.txt
./BRKGA >> resultados03.txt
./BRKGA >> resultados04.txt
./BRKGA >> resultados05.txt
./BRKGA >> resultados06.txt
./BRKGA >> resultados07.txt
./BRKGA >> resultados08.txt
./BRKGA >> resultados09.txt
./BRKGA >> resultados10.txt
./BRKGA >> resultados11.txt
./BRKGA >> resultados12.txt
./BRKGA >> resultados13.txt
./BRKGA >> resultados14.txt
./BRKGA >> resultados15.txt
./BRKGA >> resultados16.txt
./BRKGA >> resultados17.txt
./BRKGA >> resultados18.txt
./BRKGA >> resultados19.txt
./BRKGA >> resultados20.txt
./BRKGA >> resultados21.txt
./BRKGA >> resultados22.txt
./BRKGA >> resultados23.txt
./BRKGA >> resultados24.txt
./BRKGA >> resultados25.txt
./BRKGA >> resultados26.txt
./BRKGA >> resultados27.txt
./BRKGA >> resultados28.txt
./BRKGA >> resultados29.txt
./BRKGA >> resultados30.txt
./BRKGA >> resultados31.txt
./BRKGA >> resultados32.txt
./BRKGA >> resultados33.txt
./BRKGA >> resultados34.txt
./BRKGA >> resultados35.txt
./BRKGA >> resultados36.txt
./BRKGA >> resultados37.txt
./BRKGA >> resultados38.txt
./BRKGA >> resultados39.txt
./BRKGA >> resultados40.txt
./BRKGA >> resultados41.txt
./BRKGA >> resultados42.txt
./BRKGA >> resultados43.txt
./BRKGA >> resultados44.txt
./BRKGA >> resultados45.txt
./BRKGA >> resultados46.txt
./BRKGA >> resultados47.txt
./BRKGA >> resultados48.txt
./BRKGA >> resultados49.txt
./BRKGA >> resultados50.txt
./BRKGA >> resultados51.txt
./BRKGA >> resultados52.txt
./BRKGA >> resultados53.txt
./BRKGA >> resultados54.txt
./BRKGA >> resultados55.txt
./BRKGA >> resultados56.txt
./BRKGA >> resultados57.txt
./BRKGA >> resultados58.txt
./BRKGA >> resultados59.txt
./BRKGA >> resultados60.txt
./BRKGA >> resultados61.txt
./BRKGA >> resultados62.txt
./BRKGA >> resultados63.txt
./BRKGA >> resultados64.txt
./BRKGA >> resultados65.txt
./BRKGA >> resultados66.txt
./BRKGA >> resultados67.txt
./BRKGA >> resultados68.txt
./BRKGA >> resultados69.txt
./BRKGA >> resultados70.txt
./BRKGA >> resultados71.txt
./BRKGA >> resultados72.txt
./BRKGA >> resultados73.txt
./BRKGA >> resultados74.txt
./BRKGA >> resultados75.txt
./BRKGA >> resultados76.txt
./BRKGA >> resultados77.txt
./BRKGA >> resultados78.txt
./BRKGA >> resultados79.txt
./BRKGA >> resultados80.txt
./BRKGA >> resultados81.txt
./BRKGA >> resultados82.txt
./BRKGA >> resultados83.txt
./BRKGA >> resultados84.txt
./BRKGA >> resultados85.txt
./BRKGA >> resultados86.txt
./BRKGA >> resultados87.txt
./BRKGA >> resultados88.txt
./BRKGA >> resultados89.txt
./BRKGA >> resultados90.txt
./BRKGA >> resultados91.txt
./BRKGA >> resultados92.txt
./BRKGA >> resultados93.txt
./BRKGA >> resultados94.txt
./BRKGA >> resultados95.txt
./BRKGA >> resultados96.txt
./BRKGA >> resultados97.txt
./BRKGA >> resultados98.txt
./BRKGA >> resultados99.txt
./BRKGA >> resultados100.txt